/**
 * Created by lmy on 2017/2/8.
 */
/**
 * Created by lmy on 2017/1/28.
 */
// Generated by CoffeeScript 1.10.0
(function() {
    module.exports = function(grunt) {
        grunt.initConfig({
            pkg: grunt.file.readJSON('package.json'),
            clean: {
                build: {
                    src: ['./build/*', './build/.*', './build/*.*']
                },
                release: {
                    src: ['./dist/*', './dist/.*', './dist/*.*']
                },
                map: {
                    src: ['./build/assets/js/main.min.js.map']
                },
                temp: {
                    src: ["./temp"]
                }
            },
            connect: {
                server: {
                    options: {
                        keepalive: true,
                        port: 80,
                        base: 'build',
                        open: true
                    }
                },
                release: {
                    options: {
                        keepalive: true,
                        port: 80,
                        base: 'dist',
                        open: true
                    }
                }
            },
            copy: {
                build: {
                    files: [
                        {
                            src: './src/favicon.ico',
                            dest: './build/favicon.ico'
                        }, {
                            src: './index.html',
                            dest: './build/index.html'
                        }, {
                            expand: true,
                            cwd: './',
                            src: ['./views/*.html'],
                            dest: './build/assets'
                        }, {
                            expand: true,
                            cwd: './bower_components',
                            src: ['ueditor/**/*.*'],
                            dest: './build/assets'
                        }, {
                            src: './bower_components/angular/angular.js',
                            dest: './build/assets/js/angular.min.js'
                        }, {
                            src: './bower_components/tendina.min.js',
                            dest: './build/assets/js/tendina.min.js'
                        }, {
                            src: './bower_components/wangEditor.min.js',
                            dest: './build/assets/js/wangEditor.min.js'
                        }, {
                            src: './public/js/app.js',
                            dest: './build/assets/js/app.js'
                        }, {
                            src: './bower_components/jquery/dist/jquery.js',
                            dest: './build/assets/js/jquery.min.js'
                        }, {
                            expand: true,
                            cwd: './bower_components/bootstrap/dist',
                            src: ['fonts/**/*.*'],
                            dest: './build/assets'
                        }, {
                            expand: true,
                            cwd: './public',
                            src: ['images/*.*'],
                            dest: './build/assets'
                        }
                    ]
                },
                release: {
                    files: [
                        {
                            src: './src/app.config.js',
                            dest: './dist/app.config.js'
                        }, {
                            expand: true,
                            cwd: './src/assets',
                            src: ['img/**/*.*', 'js/**/*.js', 'views/*.html'],
                            dest: './dist/assets'
                        }, {
                            src: './bower_components/angular/angular.js',
                            dest: './dist/assets/js/angular.min.js'
                        }, {
                            expand: true,
                            cwd: './bower_components/bootstrap/dist',
                            src: ['fonts/**/*.*'],
                            dest: './dist/assets'
                        }, {
                            src: './src/index.html',
                            dest: './dist/index.html'
                        }, {
                            src: './bower_components/jquery/dist/jquery.min.js',
                            dest: './dist/assets/js/jquery.min.js'
                        }, {
                            src: './bower_components/tendina.min.js',
                            dest: './dist/assets/js/tendina.min.js'
                        },{
                            src: './bower_components/wangEditor.min.js',
                            dest: './build/assets/js/wangEditor.min.js'
                        }
                    ]
                }
            },
            concat: {
                release: {
                    files: [
                        {
                            src: ['./bower_components/angular-ui-router/release/angular-ui-router.min.js', './other/ngDialog.min.js', './other/ng-img-crop.js'],
                            dest: './dist/assets/js/angular-widget.min.js'
                        }, {
                            src: ['./other/citypicker/CityPicker.js', './other/layer/layer.js'],
                            dest: './temp/other.js'
                        }, {
                            src: ['./public/css/**.css'],
                            dest: './temp/main.css'
                        }
                    ]
                },
                build: {
                    files: [
                        {
                            src: ['./bower_components/angular-ui-router/release/angular-ui-router.min.js'],
                            dest: './build/assets/js/angular-widget.min.js'
                        }, {
                            src: ['./bower_components/bootstrap/dist/js/bootstrap.min.js','./bower_components/bootstrap/dist/js/bootstrap-paginator.js','./ueditor/ueditor.config.js','./ueditor/ueditor.all.min.js','./ueditor/lang/zh-cn/zh-cn.js'],
                            dest: './build/assets/js/other.min.js'
                        }, {
                            src: ['./public/js/**.js',"./public/js/**/**.js"],
                            dest: './build/assets/js/app.js'
                        },{
                            src: './bower_components/wangEditor.min.js',
                            dest: './build/assets/js/wangEditor.min.js'
                        },{
                            src: ['./bower_components/bootstrap/dist/css/bootstrap.min.css', './public/css/**.css'],
                            dest: './build/assets/css/main.css'
                        }
                    ]
                }
            },
            cssmin: {
                release: {
                    files: [
                        {
                            src: "./temp/**.css",
                            dest: "./dist/assets/css/main.min.css"
                        }
                    ]
                }
            },
            uglify: {
                release: {
                    files: [
                        {
                            src: './temp/main.js',
                            dest: './dist/assets/js/main.min.js'
                        }, {
                            src: './temp/other.js',
                            dest: './dist/assets/js/other.min.js'
                        }
                    ]
                }
            },
            watch: {
                options: {
                    spawn: false,
                    livereload: true
                },
                build: {
                    files: ['./views/**.html','./index.html','./public/**/*.css', './public/**/*.js'],
                    tasks: ['clean:build', 'copy:build', 'concat:build', 'clean:map']
                }
            },
            usemin: {
                html: 'dist/index.html'
            }
        });
        grunt.loadNpmTasks('grunt-contrib-clean');
        grunt.loadNpmTasks('grunt-contrib-concat');
        grunt.loadNpmTasks('grunt-contrib-connect');
        grunt.loadNpmTasks('grunt-contrib-copy');
        grunt.loadNpmTasks('grunt-contrib-uglify');
        grunt.loadNpmTasks('grunt-contrib-watch');
        grunt.loadNpmTasks('grunt-contrib-cssmin');
        grunt.loadNpmTasks('grunt-usemin');
        grunt.registerTask('build', ['clean:build', 'copy:build', 'concat:build', 'clean:map', 'watch:build']);
        grunt.registerTask('default',['clean','concat','connect','copy','uglify','watch','cssmin','usemin']);
    };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
